// <auto-generated />
using System;
using Fleans.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleans.Persistence.PostgreSql.Migrations.Query
{
    [DbContext(typeof(FleanQueryDbContext))]
    partial class FleanQueryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleans.Domain.ProcessDefinition", b =>
                {
                    b.Property<string>("ProcessDefinitionId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BpmnXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ProcessDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("Workflow")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Workflow");

                    b.HasKey("ProcessDefinitionId");

                    b.HasIndex("ProcessDefinitionKey");

                    b.ToTable("ProcessDefinitions", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.ActivityInstanceEntry", b =>
                {
                    b.Property<Guid>("ActivityInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ChildWorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ExecutionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExecuting")
                        .HasColumnType("boolean");

                    b.Property<int?>("MultiInstanceIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("MultiInstanceTotal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariablesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityInstanceId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowActivityInstanceEntries", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.ConditionSequenceState", b =>
                {
                    b.Property<Guid>("GatewayActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionalSequenceFlowId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("boolean");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("GatewayActivityInstanceId", "ConditionalSequenceFlowId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowConditionSequenceStates", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.GatewayForkState", b =>
                {
                    b.Property<Guid>("ForkInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumedTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedTokenIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("ForkInstanceId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("GatewayForks", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageCorrelationState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("MessageCorrelations", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageStartEventListenerState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("MessageStartEventListeners", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageStartEventRegistration", b =>
                {
                    b.Property<string>("MessageName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProcessDefinitionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MessageName", "ProcessDefinitionKey");

                    b.ToTable("MessageStartEventRegistrations", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageSubscription", b =>
                {
                    b.Property<string>("MessageName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("HostActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageName");

                    b.ToTable("MessageSubscriptions", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalCorrelationState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("SignalCorrelations", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalStartEventListenerState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("SignalStartEventListeners", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalStartEventRegistration", b =>
                {
                    b.Property<string>("SignalName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProcessDefinitionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SignalName", "ProcessDefinitionKey");

                    b.ToTable("SignalStartEventRegistrations", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalSubscription", b =>
                {
                    b.Property<string>("SignalName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("HostActivityInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("SignalName", "WorkflowInstanceId", "ActivityId");

                    b.ToTable("SignalSubscriptions", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.TimerCycleTrackingState", b =>
                {
                    b.Property<Guid>("HostActivityInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimerActivityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TimerExpression")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TimerType")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("HostActivityInstanceId", "TimerActivityId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("TimerCycleTracking", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.TimerStartEventSchedulerState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FireCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxFireCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessDefinitionId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Key");

                    b.ToTable("TimerSchedulers", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.UserTaskState", b =>
                {
                    b.Property<Guid>("ActivityInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Assignee")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CandidateGroups")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CandidateUsers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExpectedOutputVariables")
                        .HasColumnType("text");

                    b.Property<int>("TaskState")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityInstanceId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("UserTasks", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.WorkflowInstanceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ETag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ExecutionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentActivityId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentWorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessDefinitionId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("WorkflowInstances", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.WorkflowVariablesState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentVariablesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Variables");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowVariableStates", (string)null);
                });

            modelBuilder.Entity("Fleans.Persistence.Events.WorkflowEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GrainId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrainId", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowEvents", (string)null);
                });

            modelBuilder.Entity("Fleans.Persistence.Events.WorkflowSnapshotEntity", b =>
                {
                    b.Property<string>("GrainId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("GrainId");

                    b.ToTable("WorkflowSnapshots", (string)null);
                });

            modelBuilder.Entity("Fleans.Domain.States.ActivityInstanceEntry", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany("Entries")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.ConditionSequenceState", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany("ConditionSequenceStates")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.GatewayForkState", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany("GatewayForks")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageSubscription", b =>
                {
                    b.HasOne("Fleans.Domain.States.MessageCorrelationState", null)
                        .WithOne("Subscription")
                        .HasForeignKey("Fleans.Domain.States.MessageSubscription", "MessageName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalSubscription", b =>
                {
                    b.HasOne("Fleans.Domain.States.SignalCorrelationState", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("SignalName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.TimerCycleTrackingState", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany("TimerCycleTracking")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.UserTaskState", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.WorkflowInstanceState", b =>
                {
                    b.HasOne("Fleans.Domain.ProcessDefinition", null)
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Fleans.Domain.States.WorkflowVariablesState", b =>
                {
                    b.HasOne("Fleans.Domain.States.WorkflowInstanceState", null)
                        .WithMany("VariableStates")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleans.Domain.States.MessageCorrelationState", b =>
                {
                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Fleans.Domain.States.SignalCorrelationState", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Fleans.Domain.States.WorkflowInstanceState", b =>
                {
                    b.Navigation("ConditionSequenceStates");

                    b.Navigation("Entries");

                    b.Navigation("GatewayForks");

                    b.Navigation("TimerCycleTracking");

                    b.Navigation("VariableStates");
                });
#pragma warning restore 612, 618
        }
    }
}
