{{- if and .Values.auth.authority .Values.auth.clientSecret (not .Values.auth.clientSecretExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleans.auth.secretName" . }}
  labels:
    {{- include "fleans.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  client-secret: {{ .Values.auth.clientSecret | quote }}
{{- end }}
