{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleans.fullname" . }}-web
  labels:
    {{- include "fleans.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "fleans.selectorLabels" (dict "ctx" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
